export const user = {
  principal_id: 'test',
  username: 'reviewer',
  display_name: 'Reviewer',
  permissions: ['audit', 'review', 'followup', 'evaluate'],
  employee_ids: ['*'],
  case_ids: null,
  review_period: null,
  source_types: ['goal_updates'],
  evaluation_profiles: ['*'],
  expires_at: null,
}
const dim = {
  status: 'UNDETERMINED',
  reason: 'The target benchmark is missing.',
  evidence_ids: ['ev1'],
}
export const audit = {
  followup_eligible: true,
  followup_ineligible_reasons: [],
  followup_agent_profiles: ['tiny'],
  actionable_missing_information: [{ gap_id: 'g1', description: 'Provide the employee’s Q2 target.', retrievable: true }],
  run_id: 'audit_test',
  case_id: 'case_test',
  status: 'SUCCEEDED',
  parent_run_id: null,
  assessment: {
    label: 'INSUFFICIENT_INFORMATION',
    reason: 'The target benchmark is missing, so overachievement cannot be verified.',
    relevance: { ...dim, status: 'RELEVANT' },
    specificity: { ...dim, status: 'ADEQUATE' },
    claim_evidence_fit: dim,
    coverage: { ...dim, status: 'PARTIAL' },
    missing_information: [
      {
        gap_id: 'g1',
        kind: 'BENCHMARK',
        description: 'Provide the employee’s Q2 target.',
        affected_claim_part: 'Exceeded target',
        retrievable: true,
      },
    ],
    contradictions: [],
    cited_evidence_ids: ['ev1'],
  },
  human_review_required: true,
  human_review_reasons: ['RUBRIC_UNCONFIRMED'],
  error: null,
  case_snapshot: {
    case_id: 'case_test',
    employee_id: 'E001',
    criterion: 'Sales target achievement',
    claim: 'Exceeded my individual sales target in Q2',
    review_period: { start: '2026-04-01', end: '2026-06-30' },
    reference_standard: null,
    locale: 'en',
    evidence: [
      {
        evidence_id: 'ev1',
        text: 'Individual sales totaled RMB 1.2 million.',
        source_type: 'submitted',
        occurred_start: '2026-04-01',
        occurred_end: '2026-06-30',
      },
    ],
  },
  excluded_evidence: [],
  versions: { rubric: 'v0.4' },
  run_hash: 'a'.repeat(64),
  human_reviews: [],
  started_at: '2026-10-03T02:00:00Z',
  finished_at: '2026-10-03T02:00:01Z',
  usage: { api_cost_usd: null, cost_status: 'UNKNOWN' },
}
export const followup = {
  agent_run_id: 'agent_test',
  initial_run_id: 'audit_test',
  reaudit_run_id: null,
  final_run_id: 'audit_test',
  status: 'COMPLETED',
  reaudit_status: 'NOT_RUN_NO_NEW_EVIDENCE',
  stop_reason: 'NO_NEW_EVIDENCE',
  label_before: 'INSUFFICIENT_INFORMATION',
  label_after: null,
  label_changed: false,
  error: null,
  new_evidence_ids: ['ev2'],
  unreviewed_evidence_ids: ['ev2'],
  trace: [
    {
      step: 1,
      tool_name: 'search_goal_updates',
      arguments: { query: 'Sales target', limit: 5 },
      status: 'SUCCEEDED',
      returned_count: 1,
      new_evidence_ids: ['ev2'],
    },
  ],
  human_review_reasons: [],
  usage: { api_cost_usd: null, cost_status: 'UNKNOWN' },
}
export const evaluation = {
  experiment_id: 'exp_test',
  evaluation_profile: 'core_dev',
  status: 'FAILED',
  created_at: '2026-10-03T02:00:00Z',
  finished_at: '2026-10-03T02:02:00Z',
  progress: { completed_tasks: 1, total_tasks: 6 },
  error: { error_code: 'TIME_LIMIT' },
  summary: {
    case_count: 2,
    dataset_version: 'test',
    rubric_version: 'v0.4',
    groups: [
      {
        name: 'rule',
        case_count: 1,
        completed_count: 1,
        correct_count: 0,
        failed_count: 1,
        accuracy: 0,
        execution_success_rate: 0,
        macro_f1: 0,
        macro_f1_definition: 'Failures are included.',
        per_class: { SUPPORTED: { count: 1, predicted_count: 0, precision: 0, recall: 0, f1: 0 } },
        confusion_matrix: {
          SUPPORTED: {
            SUPPORTED: 0,
            PARTIALLY_SUPPORTED: 0,
            UNSUPPORTED: 0,
            INSUFFICIENT_INFORMATION: 0,
            FAILED: 1,
          },
        },
        false_support: {
          count: 0,
          denominator: 0,
          rate: null,
          by_gold_label: {},
          denominator_definition: 'Non-supported reference cases.',
        },
        api_cost_usd: null,
        cost_status: 'UNKNOWN',
        duration_seconds: { total: 1, mean: 1, p95: 1 },
      },
    ],
  },
  results: [
    {
      case_id: 'case_test',
      group: 'rule',
      run_id: 'audit_test',
      gold_label: 'SUPPORTED',
      predicted_label: null,
      error: { error_code: 'TIME_LIMIT' },
      duration_seconds: 1,
      api_cost_usd: null,
      cost_status: 'UNKNOWN',
    },
  ],
}
